import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import '../core/app_state.dart';
import '../widgets/common.dart';

class BillingNativeScreen extends StatefulWidget{const BillingNativeScreen({super.key,required this.state});final AppState state;@override State<BillingNativeScreen> createState()=>_S();}
class _S extends State<BillingNativeScreen>{Map<String,dynamic>? data;bool busy=false;
 @override void initState(){super.initState();load();}
 Future<void> load()async{setState(()=>busy=true);try{final r=await widget.state.api.request('billing/info');if(mounted){setState(()=>data=r);widget.state.updateSubscription(r['subscription']);}}catch(e){if(mounted)snack(context,'$e',error:true);}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> copy(String value,String label)async{await Clipboard.setData(ClipboardData(text:value));if(mounted)snack(context,'$label kopyalandı.');}
 Future<void> notifyPayment()async{final c=Map<String,dynamic>.from(data?['company']??{});final payer=TextEditingController(text:'${c['company_name']??''}');final amount=TextEditingController(text:'${c['monthly_price']??''}');final bank=TextEditingController();final note=TextEditingController();DateTime date=DateTime.now();final ok=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setS)=>AlertDialog(title:const Text('Ödeme Bildirimi'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:payer,decoration:const InputDecoration(labelText:'Ödeme Yapan *')),const SizedBox(height:10),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Tutar *')),const SizedBox(height:10),ListTile(contentPadding:EdgeInsets.zero,title:const Text('Ödeme Tarihi'),subtitle:Text(DateFormat('dd.MM.yyyy').format(date)),trailing:const Icon(Icons.calendar_month),onTap:()async{final d=await showDatePicker(context:x,firstDate:DateTime(2020),lastDate:DateTime.now(),initialDate:date);if(d!=null)setS(()=>date=d);}),TextField(controller:bank,decoration:const InputDecoration(labelText:'Gönderen Banka')),const SizedBox(height:10),TextField(controller:note,maxLines:2,decoration:const InputDecoration(labelText:'Not'))])),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Bildir'))])));if(ok!=true)return;try{await widget.state.api.request('billing/notify',method:'POST',data:{'payer_name':payer.text,'amount':amount.text,'payment_date':DateFormat('yyyy-MM-dd').format(date),'bank_name':bank.text,'note':note.text});if(mounted)snack(context,'Ödeme bildiriminiz alındı.');await load();}catch(e){if(mounted)snack(context,'$e',error:true);}}
 Widget row(String label,String value,{bool copyable=false})=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(fontSize:11,color:Colors.grey)),const SizedBox(height:2),SelectableText(value,style:const TextStyle(fontWeight:FontWeight.w800))])),if(copyable)IconButton(tooltip:'Kopyala',onPressed:()=>copy(value,label),icon:const Icon(Icons.copy_rounded))]));
 @override Widget build(BuildContext context){if(data==null)return Scaffold(appBar:AppBar(title:const Text('Paket ve Ödeme')),body:Center(child:busy?const CircularProgressIndicator():FilledButton(onPressed:load,child:const Text('Tekrar Dene'))));final c=Map<String,dynamic>.from(data!['company']??{}),s=Map<String,dynamic>.from(data!['subscription']??{}),b=Map<String,dynamic>.from(data!['bank']??{});final allowed=s['allowed']==true;return Scaffold(appBar:AppBar(title:const Text('Paket ve Ödeme'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:allowed?Colors.green.shade50:Colors.orange.shade50,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(allowed?'Paketiniz Aktif':'Ödeme İşleminizi Tamamlayın',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('${s['message']??'Paketiniz aktif durumda.'}')]),),const SizedBox(height:14),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[row('Firma','${c['company_name']??''}'),row('Paket','${c['package_name']??''}'),row('Aylık Tutar','${c['monthly_price']??'-'} TL'),row('Paket Bitiş','${c['end_date']??'-'}'),row('Ödeme Toleransı','${c['grace_days']??0} gün'),row('Tolerans Sonu','${s['grace_end']??'-'}'),row('Firma Referans Kodu','${c['billing_reference']??''}',copyable:true)]))),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Banka Bilgileri',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),const SizedBox(height:8),row('Banka','${b['bank_name']??''}'),row('Hesap Adı','${b['account_name']??''}',copyable:true),row('IBAN','${b['iban']??''}',copyable:true)]))),const SizedBox(height:14),FilledButton.icon(onPressed:notifyPayment,icon:const Icon(Icons.receipt_long_outlined),label:const Text('Ödeme Yaptım / Bildirim Gönder')),if(!allowed)...[const SizedBox(height:10),OutlinedButton.icon(onPressed:widget.state.logout,icon:const Icon(Icons.logout),label:const Text('Çıkış Yap'))],const SizedBox(height:20)])));}
}
